<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <div class="field client idn">
        <label for="client_idn" class="label">
            <span>
                <?php /* @escapeNotVerified */echo __('Linkedin profile') ?>
            </span>
        </label>
        <div class="control">
            <input type="text" name="linkedin_url" id="linkedin_url"
                   <?php if($myCustomAttribute = $block->getCustomer()->getCustomAttribute('linkedin_url')) { ?>
                    value="<?= $myCustomAttribute->getValue(); ?>"
                   <?php } ?>
                   title="<?php /* @escapeNotVerified */ echo __('Linkedin profile') ?>" class="input-text"
                   data-validate='{"required":true, "url": true, "maxlength":250}'
            />
        </div>
    </div>
</fieldset>
