<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <div class="field Linkedin profile">
        <label for="linkedin_profile" class="label">
            <span>
                <?php /* @escapeNotVerified */echo __('Linkedin profile') ?>
            </span>
        </label>
        <div class="control">
            <input type="text" name="linkedin_profile" id="linkedin_profile"
                   title="<?php /* @escapeNotVerified */ echo __('Linkedin profile') ?>"
                   class="input-text" data-validate='{"required":true, "url": true, "maxlength":250}'
            />
        </div>
    </div>
</fieldset>
